version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustive
    - exhaustruct_v5
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godox
    - ireturn
    - lll
    - mnd
    - nestif
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - perfsprint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - testpackage
    - thelper
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl_v5
    # Deprecated but not yet removed. Retained here to silence deprecation warning
    - exhaustruct
    - gomodguard
    - wsl
  settings:
    gocritic:
      disabled-checks:
        - appendAssign
        - ifElseChain
        - dupArg
  exclusions:
    generated: lax
    rules:
      - linters:
          - err113
        path: ^[^/]*$
      - path: (.+)\.go$
        text: ^don't use ALL_CAPS
      - path: (.+)\.go$
        text: '^ST1003: should not use ALL_CAPS'
      - path: (.+)\.go$
        text: '^G304: Potential file inclusion via variable'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
