issues:
  exclude-use-default: false
  exclude:
    - "^don't use ALL_CAPS"
    - "^ST1003: should not use ALL_CAPS"
    - "^G304: Potential file inclusion via variable"
  exclude-rules:
    # Dynamic errors are OK in main (top-level dir). Packages should use sentinels.
    - path: "^[^/]*$"
      linters:
        - err113

linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godox
    - ireturn
    - lll
    - mnd
    - nestif
    - nlreturn
    - nonamedreturns
    - paralleltest
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - tenv
    - testpackage
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl

linters-settings:
  gocritic:
    disabled-checks:
      - appendAssign # Perfectly valid to assign to a different var
      - ifElseChain # This is taste and cannot be determined automatically
      - dupArg # False positive with self-equality tests, not useful either
